### ISSUE TITLE
Add spec/ for each module

### ISSUE THREAD

**Issue by joe-bowman** [ingenuity-build/quicksilver#18]
We should write a spec for each module. Osmosis does this particularly well with the following sections for each Module:

1. Concepts
2. State
3. Events
4. Keeper
5. React Hooks
6. Queries
7. Params

---
- [ ] Spec for interchainstaking
- [ ] Spec for interchaiqueries
- [ ] Spec for epoch
- [ ] Spec for claims
- [ ] Spec for airdrops

**Comment by joe-bowman** [comment]
This was address previously
